// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketero.Infrastructure.Data;

#nullable disable

namespace Ticketero.Infrastructure.Migrations
{
    [DbContext(typeof(TicketeroDbContext))]
    [Migration("20260706062315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticketero.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Icono")
                        .HasColumnType("image");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_AreasFase_Descripcion");

                    b.HasIndex("Prefijo")
                        .IsUnique()
                        .HasDatabaseName("UQ_AreasFase_Prefijo");

                    b.ToTable("AreasFase", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Atencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AtencionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueDerivado")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int?>("SesionOperadorId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoAtencionSegundos")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaDestinoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("EstadoTicketId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("SesionOperadorId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Atencion", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfiguracionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("UQ_Configuraciones_Clave");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Configuraciones_Estado");

                    b.ToTable("Configuraciones", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.ConfiguracionKiosko", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfiguracionKioskoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoImpresora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EstadoMultimedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormatoMultimedia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Impresora")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpEquipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpImpresora")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KioskoId")
                        .HasColumnType("int");

                    b.Property<string>("MascaraRed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PuertoImpresora")
                        .HasColumnType("int");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RutaMultimedia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TiempoMultimediaSegundos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_ConfiguracionKiosko_Estado");

                    b.HasIndex("KioskoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConfiguracionKiosko");

                    b.ToTable("ConfiguracionKiosko", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.EstadoTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstadoTicketId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_EstadosTicket_Descripcion");

                    b.ToTable("EstadosTicket", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Kiosko", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KioskoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Kiosko_Descripcion");

                    b.ToTable("Kiosko", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Marcacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MarcacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaMarcacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<int>("KioskoId")
                        .HasColumnType("int");

                    b.Property<byte>("NumeroLlamado")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Respondio")
                        .HasColumnType("bit");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KioskoId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Marcacion", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrioridadId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Nivel")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Prioridades_Descripcion");

                    b.HasIndex("Nivel")
                        .IsUnique()
                        .HasDatabaseName("UQ_Prioridades_Nivel");

                    b.ToTable("Prioridades", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PuestoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Puestos_Area_Descripcion");

                    b.ToTable("Puestos", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<int>("Logs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Descripcion");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServicioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Servicios_Area_Descripcion");

                    b.ToTable("Servicios", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.SesionOperador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SesionOperadorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PuestoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionOperador", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaActualId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoTicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaActualId");

                    b.HasIndex("EstadoTicketId");

                    b.HasIndex("NumeroTicket")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tickets_NumeroTicket");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TipoTicketId");

                    b.ToTable("Tickets", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.TipoTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoTicketId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique()
                        .HasDatabaseName("UQ_TiposTicket_Descripcion");

                    b.ToTable("TiposTicket", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoSistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Logs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSistema")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_CodigoSistema");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Correo");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.UsuarioArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioAreaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaReg")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Ride")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("UsuarioId", "AreaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UsuariosAreaFase");

                    b.ToTable("UsuariosAreaFase", "dbo");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Atencion", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Area", "AreaDestino")
                        .WithMany()
                        .HasForeignKey("AreaDestinoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ticketero.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.EstadoTicket", "EstadoTicket")
                        .WithMany("Atenciones")
                        .HasForeignKey("EstadoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Atenciones")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.SesionOperador", "SesionOperador")
                        .WithMany("Atenciones")
                        .HasForeignKey("SesionOperadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ticketero.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Atenciones")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Atenciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("AreaDestino");

                    b.Navigation("EstadoTicket");

                    b.Navigation("Servicio");

                    b.Navigation("SesionOperador");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.ConfiguracionKiosko", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Kiosko", "Kiosko")
                        .WithMany()
                        .HasForeignKey("KioskoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kiosko");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Marcacion", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Kiosko", "Kiosko")
                        .WithMany("Marcaciones")
                        .HasForeignKey("KioskoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Marcaciones")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Marcaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiosko");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Area", "Area")
                        .WithMany("Puestos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Area", "Area")
                        .WithMany("Servicios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.SesionOperador", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Puesto", "Puesto")
                        .WithMany("Sesiones")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Area", "AreaActual")
                        .WithMany("Tickets")
                        .HasForeignKey("AreaActualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.EstadoTicket", "EstadoTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("EstadoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Prioridad", "Prioridad")
                        .WithMany("Tickets")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Tickets")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.TipoTicket", "TipoTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("TipoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaActual");

                    b.Navigation("EstadoTicket");

                    b.Navigation("Prioridad");

                    b.Navigation("Servicio");

                    b.Navigation("TipoTicket");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.UsuarioArea", b =>
                {
                    b.HasOne("Ticketero.Domain.Entities.Area", "Area")
                        .WithMany("UsuariosArea")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketero.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosArea")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Area", b =>
                {
                    b.Navigation("Puestos");

                    b.Navigation("Servicios");

                    b.Navigation("Tickets");

                    b.Navigation("UsuariosArea");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.EstadoTicket", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Kiosko", b =>
                {
                    b.Navigation("Marcaciones");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Prioridad", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Puesto", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.SesionOperador", b =>
                {
                    b.Navigation("Atenciones");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Marcaciones");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.TipoTicket", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketero.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Atenciones");

                    b.Navigation("Marcaciones");

                    b.Navigation("Sesiones");

                    b.Navigation("UsuariosArea");
                });
#pragma warning restore 612, 618
        }
    }
}
